# Generated by Django 3.0.3 on 2020-02-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200218_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userId',
        ),
    ]
