# Generated by Django 3.0.3 on 2020-02-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userId',
        ),
    ]
